algoritmo "Aula Função Se com Ou"
// Função :
// Autor : Luan Patric de Castro
// Data : 05/04/2025
// Seção de Declarações 
var

         cor : caractere
inicio



         escreval("Digite uma cor: ")
         leia(cor)
         
         Se (cor = "azul") ou (cor = "amarelo") ou (cor = "preto")  Entao
         
            escreval("A cor informada é azul, amarela ou preto")
            
         Senao

              escreval("cor inválida")
              
         FimSe
fimalgoritmo
