algoritmo "Aula da Função Se"
// Função :
// Autor :  Luan Patric de Castro
// Data : 04/04/2025
// Seção de Declarações 
var

         numero : real
inicio




      escreval("Digite um numero:")
      leia (numero)
      
      Se (numero > 10) Entao
         escreval(numero, " É maior do que 10")
      
      Senao
           escreval(numero, " É menor do que 10")
      
      FimSe


fimalgoritmo
