algoritmo "Verificar Par ou ímpar"
// Função :
// Autor : Luan Patric de Castro
// Data : 08/04/2025
// Seção de Declarações 
var

   numero:inteiro

inicio


      Escreval("Informe um número maior que 0:")
      leia(numero)
      Se (numero mod 2 == 0)Entao
         Escreval("O número ", numero, " é par")
         Senao
              Escreval("O número ", numero, " é ímpar")
      FimSe
fimalgoritmo
